import { useContext } from 'react';
import CardBox from '../../shared/CardBox';
import { Alert } from 'flowbite-react';
import { HiInformationCircle } from 'react-icons/hi';
import { ImageContext } from 'src/context/ImageAiContext';
function GeneratedImageDisplay() {
  const { displayedImages, isGenerating, isUsingMock } = useContext(ImageContext);

  return (
    <CardBox>
      <div className="flex flex-col gap-4">
        <div>
          {isGenerating ? (
            <h3 className="text-xl font-bold ">Generating...</h3>
          ) : (
            <h3 className="text-xl font-bold ">Results</h3>
          )}
        </div>

        {/* Show alert only if using mock data */}
        {isUsingMock && (
          <Alert
            className="bg-lightprimary text-primary dark:bg-darkprimary dark:text-primary "
            icon={HiInformationCircle}
            rounded
          >
            These images are part of a simulated AI response for testing purposes. They were not
            generated by an actual AI system.
          </Alert>
        )}

        {isGenerating ? (
          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4">
            {[...Array(isUsingMock ? 4 : 1)].map((_, idx) => (
              <div
                key={idx}
                role="status"
                className="flex items-center justify-center h-56 max-w-sm bg-gray-300 rounded-lg animate-pulse dark:bg-gray-700"
              >
                <svg className="w-10 h-10 text-gray-200 dark:text-gray-600" />
              </div>
            ))}
          </div>
        ) : (
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
            {displayedImages.map((img: string, idx: number) => (
              <div key={idx} className="relative w-full aspect-square">
                <img
                  src={img}
                  alt={`Generated ${idx}`}
                  // fill
                  className="object-cover rounded-lg"
                />
              </div>
            ))}
          </div>
        )}
      </div>
    </CardBox>
  );
}

export default GeneratedImageDisplay;
